### ISSUE TITLE
Sidebar mobile responsive

### ISSUE THREAD

**Issue by MrWildanMD** [lk77/vuesax#10]
OS: Windows 11
NodeJS: Latest
Vuesax: Latest
Browser: Chrome v100
PackageManager: PNPM

when i try the responsiveness it run into problem when in mobile view or below 700px when the sidebar is collapsed/hidden the content is not centered
as you can see from the documentation:
![image](https://github.com/lk77/vuesax/assets/60354284/7773da85-a0e6-465d-8e2c-58f51b8f01e6)

**Comment by lk77** [comment]
i think it's an issue with the documentation, since i upgraded the theme, i will look into it

**Comment by MrWildanMD** [comment]
alright thanks for the confirmation, so i can use it normally?

**Comment by lk77** [comment]
there is no issue with vuesax3 in itself, it should be fine, you can use the vue2 documentation in the meantime : https://lusaxweb.github.io/vuesax/ it's nearly the same

**Comment by MrWildanMD** [comment]
okay thanks for the confirmation again! closed.

**Comment by lk77** [comment]
@MrWildanMD it should be fixed now
