### ISSUE TITLE
Is it possible to access $vs in Nuxt3?

### ISSUE THREAD

**Issue by yuyanghh** [lk77/vuesax#11]
I've install Vuesax as plugin in Nuxt3 by following @lk77 's instruction. 
 I'm struggling to some components, like loading and notifications, which need to inject $vs to be functional. 
Are there some ways to implement those components in Nuxt3?
Thanks in advance! 

- Your OS
 macOS 14.1.2
- Node.js version
 v20.0.0
- Vuesax version
 v4.3.0-alpha.0
- Browser version
 Arc v4.3.0-alpha.0
 Chrome Engine Version 119.0.6045.199
- Which package manager did you use for the install?
 npm

**Comment by lk77** [comment]
i think you can do that :

```js
import { inject } from 'vue'

const $vs = inject('$vs')

$vs.notify({
  title: 'Notification',
  text: 'Lorem ipsum dolor sit amet, consectetur'
})
```

it's for the composition api but i think it should work inside a nuxt component

**Comment by lk77** [comment]
I've tried it, and i think it should be wrapped in onMounted for it to work :

```js
import { inject, onMounted } from 'vue'

onMounted(() => {
  let $vs = inject('$vs')
  $vs.notify({
    title: 'Notification',
    text: 'Lorem ipsum dolor sit amet, consectetur'
  })
})
```

it seems to be working fine
