### ISSUE TITLE
[Vue warn] Hydration node mismatch in Nuxt3

### ISSUE THREAD

**Issue by yuyanghh** [lk77/vuesax#12]
I've install Vuesax as plugin in Nuxt3 by following @lk77 's instruction.
When developing, console kept complaining about Hydration node mismatch.

Error message:
```
entry.js:50 [Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM: <!---->  
  at <VsCard key="rec0iYqi6rO6KMaLj" > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" vnode= 
```

Your OS
macOS 14.1.2
Node.js version
v20.0.0
Vuesax version
v4.3.0-alpha.0
Browser version
Arc v4.3.0-alpha.0
Chrome Engine Version 119.0.6045.199
Which package manager did you use for the install?
npm

**Comment by lk77** [comment]
i will look into that, i don't really know why it does that

**Comment by lk77** [comment]
@yuyanghh 

I don't have any issue running the VsCard component inside nuxt,

![Screenshot from 2024-01-18 13-35-04](https://github.com/lk77/vuesax/assets/9606882/0664fa6a-0185-472b-aed2-2e00fcb47794)

how do you reproduce this issue ?

thanks.
