### ISSUE TITLE
Types missing

### ISSUE THREAD

**Issue by Phill030** [lk77/vuesax#2]
This cannot be used since there are no types for TypeScript
![Code_wQmnXLgCC6](https://user-images.githubusercontent.com/50775241/178108074-ab980a40-92be-4510-be41-203f1bfdbf08.png)

**Comment by lk77** [comment]
This seems to be an issue with the original package (ex: https://github.com/lusaxweb/vuesax/issues/34)

For now i have no plan to support it, you can do something like this in your typings.d.ts :

```
declare module 'vuesax3';
```

**Comment by lk77** [comment]
I added an index.d.ts https://github.com/lk77/vuesax/blob/next/index.d.ts, try to see if it fixes your issue
