### ISSUE TITLE
File css does not exist?

### ISSUE THREAD

**Issue by adibpwd** [lk77/vuesax#3]

**Comment by adibpwd** [comment]
![image](https://user-images.githubusercontent.com/54851209/183284920-d2344bb6-644e-4fcc-9cfd-ca2f2a9463fa.png)

Does not exist file css

**Comment by adibpwd** [comment]
- Xubuntu
- 16.13.2
- 4.0.22
- Chrome
- nodemodules, with npm

**Comment by adibpwd** [comment]
temporarily solved, not good but the important thing is it works first:

![image](https://user-images.githubusercontent.com/54851209/183285304-6354e4cf-4e94-4c2e-8a01-92f1a6673221.png)
![image](https://user-images.githubusercontent.com/54851209/183285334-0789e756-e389-4d8e-9699-713c50148738.png)

i'm copas css form repo to file vuesax-style.css in public/styles/ directory

**Comment by lk77** [comment]
The package name is vuesax3, vuesax refers to the old vue2 package, so the correct import is : `import 'vuesax3/dist/vuesax.css'`
