### ISSUE TITLE
how to use $vs in vue3 setup syntax?

### ISSUE THREAD

**Issue by ppxb** [lk77/vuesax#5]
when the app has install vuesax3,how to use $vs.nofity in setup syntax?
thanks so much.

**Comment by lk77** [comment]
Hello,

it does not seems to work, i can see $vs in the ctx object, using this.$vs works in Options Api but not on Composition Api

edit: 

I made a fix :

```
npm i github:lk77/vuesax#09f7429
```

tell me if it solves your issue and i will publish it.

You will need to use inject :

```
import { inject } from 'vue'

const $vs = inject('$vs')

$vs.notify(...)
```

**Comment by ppxb** [comment]
thanks for your hard working.i will try your way later and give a feedback.

**Comment by lk77** [comment]
Everything was working fine on my side, with options api and with composition api, so i published it under 4.0.24

i've also updated the docs for notify/loading/dialog functions to include a tip about composition api

**Comment by ppxb** [comment]
thanks dude,it's working fine on my side.have a nice day.

**Comment by lk77** [comment]
Great !
