### ISSUE TITLE
Would you consider to make Vuesax-next for Vue 3

### ISSUE THREAD

**Issue by Bijit-Mondal** [lk77/vuesax#8]
Please make Vuesax-next for Vue 3

**Comment by lk77** [comment]
@Bijit-Mondal I have considered it, but vuesax-next is not finished enough, there is still a lot of components to make, i'm not really sure if it's worth it

I could try to fix the existing components, but i don't think i will have time to make new ones

**Comment by Bijit-Mondal** [comment]
@lk77  Thank you for considering my question. I understand that developing vuesax-next may be time-consuming and challenging, but as a user of vuesax, I would love to see its development continue for Vue 3. If there's anything I can do to assist in the development process or if there are any specific components that you need help with, please let me know.

**Comment by lk77** [comment]
@Bijit-Mondal i looked into it, and vuesax-next is on vue 2, and is using vue-class-component, so it's a lot of work to upgrade it to vue 3

I think it will need to be migrated to composition api on vue 2.7, and get rid of vue-class-component, and then upgraded to vue 3
