### ISSUE TITLE
validation vue 3 migration

### ISSUE THREAD

**Issue by piotrm73** [lk77/vuesax#9]
Hi
What is the quickest way to migrate from vee-validate to Vue 3? Because it seems that vee-validate 4 has removed the v-validate directive and don't know why it replaced fields with something like in the following example:

```
<Field name="email" type="email" />
<ErrorMessage name="email" />
```

Should I consider using a different library? If so what library is the best to use with vuesax?

**Comment by lk77** [comment]
You should replace your v-validate directive with the components Field, ErrorMessage, Form, and so on.

that's a long and tedious process, i've done it on a big project, and it took me 3 months to do the whole migration process ( including vee-validate )

For custom components
```html
<Form>
        <Field name="label" v-slot="{ value, handleChange }">
            <label-component :modelValue="value" @update:modelValue="handleChange"></label-component>
            <ErrorMessage name="label"></ErrorMessage>
        </Field>
</Form>
```

For simple inputs
```html
<Form>
        <Field name="email"/>
        <ErrorMessage name="email" />
</Form>
```

to validate that, you either use the `:validation-schema` property on the Form, or the `:rules` property on individual Field components


To submit the form you can use the `@submit` event on the Form, it will be triggered if the form is valid when the user click on the submit button, you can also validate manually using `validate` function that is exposed by Form,

you can put a ref on the form, access it with $refs and call validate :

```html
<Form ref="createUserForm">
</Form>
```

```js
this.$refs.createUserForm.validate()
```

You can also set initial values on the Form using `:initial-values` property on the Form
You can access the values inside your template with `<Form v-slot="{ values }">`
And if you need to make a copy of a Field value, you can put a `onUpdate:modelValue` on that Field



Vuesax will work with any library you choose to use, vee-validate or another one

**Comment by piotrm73** [comment]
Thank you for the detailed explanation, but if I change the structure in this way, won't I lose all the logic of the component like v-select or vs-radio or others? I have created a component that handles form handling, and in my case it looks like this... 

```
        <v-select
                class="w-full"
                :loading="selectLoading[input.field]"
                :label-placeholder="input.headerName"
                :immediate="validationImmediate ? true : false"
                v-validate="input.validationRules"
                :data-vv-as="input.headerName"
                :name="input.field"
                :clearable="input.notClearable ? false : true"
                :append-to-body="input.appendToBody ? true : false"
                :selectable="
                  (option) =>
                    input.isSelectable
                      ? input.isSelectable(option, inputs)
                      : true
                "
                v-model="input.value"
                :disabled="input.disabled"
                :options="input.selectOptions"
                @open="onSelectActive(input.field)"
                @input="
                  input.alert
                    ? onConfirmChange($event, input)
                    : onChange($event, input)
                "
              >
              <template #no-options>
                <span>
                  Brak wyników spełniających kryteria</span>
              </template>
                
                <template #selected-option="{ label }">
                  <div
                    :class="input.labelClass"
                    style="display: flex; align-items: baseline"
                  >
                    {{ label }}
                  </div>
                </template>
                <template
                  v-if="option.icon || option.optionClass"
                  #option="option"
                  
                >
                  <div :class="!option.disabled ? option.optionClass : ''">
                    {{ option.label }}
                  </div>
                </template>
              </v-select>
```

```
           <vs-radio
                  v-for="radioOption in input.radioOptions"
                  :key="radioOption.label"
                  v-model="input.value"
                  :color="
                    input.value ? 'success' : 'warning'
                  "
                  v-validate="input.validationRules"
                  :immediate="validationImmediate ? true : false"
                  :data-vv-as="input.headerName"
                  class="mt-2 mr-2"
                  :vs-name="input.field"
                  icon-no-border
                  :label-placeholder="input.headerName"
                  @input="
                    input.alert
                      ? onConfirmChange($event, input)
                      : onChange($event, input)
                  "
                  :vs-value="radioOption.value"
                  >{{ radioOption.label }}</vs-radio
                >
```

So I think I have to look for a different library or maybe I can wrap these components with this Field component somehow?

**Comment by lk77** [comment]
You can wrap your components in a Field component, i use both vuesax a vee-validate 4 vithout issues

```
<Field v-slot="{ value, handleChange }">
    <vs-switch :modelValue="value" @update:modelValue="handleChange"/>
</Field>
```

You can also use html components 

```
<Field v-slot="{ value, handleChange }">
     <input :value="value" @change="handleChange"/>
</Field>
```

And vee-validate can even handle that for you, so :

```
<Field>
     <input />
</Field>
```
will also work, it's only usefull if you need to customize the logic and only update the value when you want

You should also look at the `validateOnBlur`, `validateOnChange`, `validateOnInput`, `validateOnModelUpdate` props, it allows you to be more specific, if for example you want your fields to be validated on change, but not on input.


If you need to customize the logic even more, and have a custom function, you will need to pass the slot `handleChange` to your function, and also the `$event` (which is the value passed to the `@update:modelValue`  (for native events your likely want to pass `$event.target.value` instead):


```
<Field v-slot="{ value, handleChange }">
    <vs-switch :modelValue="value" @update:modelValue="$updateField(handleChange, 'my_field', $event)"/>
</Field>
```

```
<Field v-slot="{ value, handleChange }">
    <input :value="value" @change="$updateField(handleChange, 'my_other_field', $event.target.value)"/>
</Field>
```

**Comment by piotrm73** [comment]
oof... I managed to figure it out
thanks!

ps. this code works if anyone needs it

```
                   <Field name="email" v-model="email" v-slot="{ field, value, errorMessage }" rules="required|email">
                      <vs-input
                      icon="icon icon-user"
                      icon-pack="feather"
                      label-placeholder="Email"
                      class="w-full no-icon-border"
                      v-bind="field"
                      :modelValue="value"
                      />
                      <span class="text-danger text-sm">{{ errorMessage }}</span>
                  </Field>
```
